# Generated by Django 5.2.7 on 2026-01-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='valido_hasta',
        ),
    ]
