# Generated by Django 5.2.7 on 2026-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
