# Generated by Django 5.2.7 on 2026-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_cita_especialidad_cita_estado_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
