# Generated by Django 5.2.7 on 2026-01-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='motivo',
        ),
    ]
