# Generated by Django 5.2.7 on 2026-01-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_cita_estado_cita'),
        ('medicos', '0002_alter_medico_especialidad'),
        ('pacientes', '0002_paciente_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicos.medico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
    ]
