# Generated by Django 5.2.7 on 2026-01-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_cita_medico_alter_cita_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
