# Generated by Django 5.2.7 on 2026-01-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('num_doc', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=3, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personales_patologicos', models.TextField(blank=True, null=True, verbose_name='Antecedentes Personales Patológicos')),
                ('personales_no_patologicos', models.TextField(blank=True, null=True, verbose_name='Antecedentes Personales No Patológicos')),
                ('heredofamiliares', models.TextField(blank=True, null=True, verbose_name='Antecedentes Heredofamiliares')),
                ('gineco_andrologicos', models.TextField(blank=True, null=True, verbose_name='Antecedentes Ginecoobstétricos / Andrológicos')),
                ('otros', models.TextField(blank=True, null=True, verbose_name='Otros antecedentes')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
        ),
    ]
