# Generated by Django 5.2.7 on 2026-01-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
