# Generated by Django 5.2.7 on 2026-01-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('medio', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('monto_pendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pendiente')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
