# Generated by Django 5.2.7 on 2026-01-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_especialidad_activo'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especialidades.especialidad'),
        ),
    ]
