# Generated by Django 5.2.7 on 2025-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicio_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
