# Generated by Django 5.2.7 on 2025-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
