# Generated by Django 5.2.7 on 2025-11-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servicios', 'Servicios'), ('pacientes', 'Pacientes'), ('medicos', 'Médicos'), ('especialidades', 'Especialidades')], max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('filtro', models.CharField(choices=[('none', 'Sin filtros'), ('activos', 'Activos'), ('inactivos', 'Inactivos'), ('mayor_uso', 'Mayor uso')], default='none', max_length=50)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('opciones_adicionales', models.CharField(blank=True, max_length=100, null=True)),
                ('ordenar_por', models.CharField(blank=True, choices=[('fecha', 'Fecha'), ('nombre', 'Nombre'), ('categoria', 'Categoría')], max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
