# Generated by Django 5.2.7 on 2026-01-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
